// app/layout.tsx
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import "@/app/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50">
        <Navbar />

        <div className="flex lg:flex-row flex-col ">
          {/* Sidebar */}

          {/* Konten */}
          <div className="flex flex-col justify-between w-full min-h-screen">
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
