// app/layout.tsx
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import "@/app/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50">
        <div className="grid grid-cols-6">
          <div className="col-span-2">
            <Navbar />
          </div>
          <div className="col-span-4">
            <div className="flex lg:flex-row flex-col ">
              {/* Konten */}
              <div className="flex flex-col justify-between w-full min-h-screen">
                {children}
                <Footer />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
