// app/layout.tsx
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import "@/app/globals.css";
// import LoadingModal from "../components/loading/loadingModal";
// import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import SaleSidebar from "@/app/components/saleSidebar";
export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* <LoadingModal /> 👈 Tempatkan di sini, di atas konten */}
        {/* <Toaster position="top-center" reverseOrder={false} /> */}
        <div className="lg:block ">
          <Navbar />
          <div className="flex flex-col lg:flex-row min-h-screen ">
            <SaleSidebar />
            <div className=" min-h-screen flex justify-between flex-col w-full ">
              {children}
              <Footer />
            </div>
          </div>
        </div>

        <div className="lg:hidden block">
          <Navbar /> {/* Sticky utama */}
          {/* Navbar Sale mobile */}
          <SaleSidebar />
          <div className="flex flex-col min-h-screen">
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
